### ISSUE TITLE
如何启动 macOS 版本

### ISSUE THREAD

**Issue by Him188** [autodotua/FrpGUI#3]
![image](https://github.com/autodotua/FrpGUI/assets/12100985/d6dfad75-1819-4125-881d-de27e113d33a)

release 说要用命令行启动, 但似乎没有如何启动的说明

**Comment by f-shake** [comment]
由于我没有任何苹果设备，因此macOS的操作是在虚拟机完成的。因缺少mac软件开发经验，且缺乏需求，因此暂时没有制作安装包，需要从命令行启动。

具体的启动方式如下：

1. 将所有文件解压到一个文件夹下
![image](https://github.com/autodotua/FrpGUI/assets/26277009/66ae55a3-f8e6-4bf0-82d7-a8f8044be7ef)

2. 打开macOS的终端并cd到该目录
![image](https://github.com/autodotua/FrpGUI/assets/26277009/07b50068-7e59-4e2d-a9e0-857e4acd9023)

3. 执行`./FrpGUI.Avalonia.Desktop`，打开软件
![image](https://github.com/autodotua/FrpGUI/assets/26277009/a7ac10e3-a367-4f17-a7aa-5a08b1aeebd6)


麻烦请尝试该方法在其他设备上是否可用，若可行，将补充到ReadMe中。

**Comment by Him188** [comment]
上次换传统命令行跑frpc了，下次用的话会试试
